# Generated by Django 3.2.16 on 2023-02-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Location_ID', models.IntegerField()),
                ('Barcode_Rm', models.CharField(max_length=255)),
                ('Barcode_Add', models.CharField(max_length=255)),
                ('Qty', models.IntegerField()),
                ('Manufacturer_ID', models.IntegerField()),
            ],
        ),
    ]
