# Generated by Django 4.2.1 on 2023-05-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CO2',
        ),
        migrations.AlterModelTable(
            name='homeitparts',
            table='HomeItParts',
        ),
    ]
