# Generated by Django 4.2.1 on 2023-05-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_co2_alter_homeitparts_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itparts',
            table='ItParts',
        ),
    ]
