# Generated by Django 4.2.1 on 2023-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inventorychange_user_alter_inventorychange_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
