# Generated by Django 4.2.1 on 2023-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_barcode_user_alter_inventorychange_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorychange',
            name='change_value',
            field=models.IntegerField(default=0),
        ),
    ]
