# Generated by Django 4.2.1 on 2023-05-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_itparts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=255)),
                ('change_value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='inventory_change', to='home.itparts')),
            ],
        ),
    ]
